<a href="https://colab.research.google.com/github/datamind-dotfit/python_for_data_science/blob/master/Python_for_data_science_answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Datamind - Python for Data Science<center>
Welcome to Python for Data Science! Today we'll deep dive into the world of Pandas, dataframes and dataframe operations. You may copy this notebook to your local Google Drive or computer to study the questions and answers later on. If you're not familiar with notebooks, please see https://jupyter-notebook.readthedocs.io/en/latest/notebook.html#notebook-documents for a quick introduction to Jupyter notebooks. These principles are directly applicable to Google Colabs notebooks.

The notebook is divided into four sections, each step requires input from the previous step(s). If you have any questions, feel free to ask them in class or contact one of the trainers per e-mail!
    
**Some tips to get you started:**
- Make new cells! You can make as many as you want, this way you can execute small code blocks and work iteratively.
- Break larger problems down into small chunks (and work them out in individual code cells). Once you're convinced everything is in order, you can merge your code into one code cell.
- Use comments to explain what you're doing, `#` allows you to write inline comments.
- If you resort to Google or Stackoverflow for help, make sure you actually understand the solution that is provided. And rather than copying the code, make sure <u>*you*</u> write the code!


---

# <center> Part one: getting data from the web. <center>
## Getting data using `wget`
Before we start, let's first get some data. In Google Colabs you can execute shell commands by adding an exclamation like shown below. The `wget` command is a built-in utility that allows retrieving files from the web. Executing a shell command means that this is no python code! Any commands that you find throughout this notebook that start with `!` are not usable in python code directly. For this you'll have to look into different solutions.

**Note:** <br>The wget command only works on the Google Colabs environment or some Linux based systems. To run this locally, download the data by hand (by copying the links into a browsers) or change the command to whatever is applicable for your OS.

In [1]:
! wget https://github.com/datamind-dotfit/python_for_data_science/raw/master/observations.xlsx https://github.com/datamind-dotfit/python_for_data_science/raw/master/sales.xlsx

/bin/sh: wget: command not found


## Verify data retrieval
Let's verify that the data was actually retrieved and stored in the working directory. We can use the shell command `ls` for this, this command lists all the files in the current directory. We should see both `observations.xlsx` and `sales.xlsx` in the result. As you may notice, there may be some other files in the directory, these files are there by default (or are located on your computer).

In [1]:
! ls

Python_for_data_science_ex3.ipynb
Python_for_data_science_ex3_answers.ipynb
observations.xlsx
sales.xlsx



# <br><center>Part two: Loading data</center>
---
## Import Pandas
To load data we first have to import the Pandas module. After importing pandas, we can use many of its useful features to work with our data. In python we can import modules using the `import` statement. 


Load the pandas module and make sure you can access its functions through the name 'pd'. Remember in python we can import modules like so: <br>`import module_name as some_shorthand`

In [2]:
import pandas as pd

## Load in the data
For this part we'll use the Pandas reader to load our files. Check what kind of file we downloaded in part one, and use the appropriate function to read both files in as data frames. See http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html for more information.

#### Question:
- What kind of files are we dealing with?
- Read in the sales data as `sales` and the observations data as `observations`

In [ ]:
# The files we are dealing with are excel files

In [4]:
# We can use the Pandas read_excel function to read the data directly. 
sales = pd.read_excel('sales.xlsx')
observations = pd.read_excel('observations.xlsx')


# <br><center>Part three: data exploration & cleaning </center>
---
## 3.1 - Explore the data 
Once we have the data loaded, it's time to explore! Let's start of by answering the following questions:

#### Questions: 
- Inspect the top five and bottom five rows of the `sales` dataframe. What's going on here?
- What's up with these column names, is this an error? Download the files by hand and see for yourself
- We would like to sample 20 rows from the data frame at random, write the code for this.
- Check out the seemingly empty columns. Which unique values do they contain? Is there anything other than NaN?
- Create descriptive statistics of **both** data frames.

In [5]:
# The head() and tail() function display the top and bottom rows.
sales.head(5)
sales.tail(5)

name_of_country  year  bikes  Unnamed: 3  Unnamed: 4 name_of_country.1  \
38     SWITZERLAND  1676     73         NaN         NaN       SWITZERLAND   
39     SWITZERLAND  1677     70         NaN         NaN       SWITZERLAND   
40     SWITZERLAND  1678     71         NaN         NaN       SWITZERLAND   
41     SWITZERLAND  1679     66         NaN         NaN       SWITZERLAND   
42     SWITZERLAND  1680     69         NaN         NaN       SWITZERLAND   

    year.1  total_turnover  
38    1676          6380.2  
39    1677          6118.0  
40    1678          6205.4  
41    1679          5768.4  
42    1680          6030.6

In [ ]:
# The unnamed columns are actually columns in the data which are empty and have no name.

In [6]:
# Sample works on a DataFrame
sales.sample(20)

name_of_country  year  bikes  Unnamed: 3  Unnamed: 4 name_of_country.1  \
28     NETHERLANDS  1674     57         NaN         NaN       NETHERLANDS   
8           FRANCE  1673     49         NaN         NaN            FRANCE   
18         GERMANY  1673     48         NaN         NaN           GERMANY   
3          AUSTRIA  1675     58         NaN         NaN           AUSTRIA   
21         GERMANY  1677     44         NaN         NaN           GERMANY   
1          AUSTRIA  1671     59         NaN         NaN           AUSTRIA   
30     NETHERLANDS  1676     54         NaN         NaN       NETHERLANDS   
35     SWITZERLAND  1673     68         NaN         NaN       SWITZERLAND   
5          AUSTRIA  1677     50         NaN         NaN           AUSTRIA   
17         GERMANY  1672     56         NaN         NaN           GERMANY   
14          FRANCE  1680     56         NaN         NaN            FRANCE   
34     SWITZERLAND  1672     69         NaN         NaN       SWITZERLAND   
12          FRANCE  1677     60         NaN         NaN            FRANCE   
6          AUSTRIA  1678     57         NaN         NaN           AUSTRIA   
36     SWITZERLAND  1674     66         NaN         NaN       SWITZERLAND   
4          AUSTRIA  1676     56         NaN         NaN           AUSTRIA   
13          FRANCE  1678     55         NaN         NaN            FRANCE   
0          AUSTRIA  1670     60         NaN         NaN           AUSTRIA   
26     NETHERLANDS  1672     54         NaN         NaN       NETHERLANDS   
40     SWITZERLAND  1678     71         NaN         NaN       SWITZERLAND   

    year.1  total_turnover  
28    1674          4936.2  
8     1673          4321.8  
18    1673          4099.2  
3     1675          5098.2  
21    1677          3757.6  
1     1671          5186.1  
30    1676          4676.4  
35    1673          5943.2  
5     1677          4395.0  
17    1672          4782.4  
14    1680          4939.2  
34    1672          6030.6  
12    1677          5292.0  
6     1678          5010.3  
36    1674          5768.4  
4     1676          4922.4  
13    1678          4851.0  
0     1670          5274.0  
26    1672          4676.4  
40    1678          6205.4

In [7]:
# We may use the unique() function on a column (Series in Pandas), there are multiple ways to write this.
sales['Unnamed: 3'].unique()
sales.loc[:, 'Unnamed: 3'].unique()
sales.iloc[:, 3].unique()

# Note: this one only works if the column names have no spaces and are no reserved words such as product or apply.
sales.name_of_country.unique() 

array(['AUSTRIA', 'FRANCE', 'GERMANY', 'NETHERLANDS', 'SWITZERLAND'],
      dtype=object)

In [ ]:
# Create descriptive statistics of both data frames.
sales.describe()
observations.describe()

---
## 3.2 - Selecting with pandas' iloc
Remember that you can use Pandas' `iloc` functionality to access information by integer index `df.iloc[4]`. We may also select columns *directly* by index using `df.iloc[:, 3]`, or select columns *after* doing an `iloc` selection using `df.iloc[5]['ColumnName']`. 

#### Questions:
- Inspect the top of the observations dataframe. What do you notice about the format of the data? How does it compare to the sales dataframe?
- Find the name of the country and the year in the sixth row of the sales dataframe.




In [8]:
# For the top rows, we may use head() again.
observations.head()

# The observations data frame is clean compared to the sales data frame. Country names are capitalized, column
# names follow the same standard.

countryname  year  pop
0     Austria  1670   85
1     Austria  1671   83
2     Austria  1672   86
3     Austria  1673   81
4     Austria  1674   75

In [9]:
# Using iloc and column selection in sequence.
sales.iloc[5][['name_of_country', 'year']]

# Using iloc for both rows & columns.
sales.iloc[5, 0:2]

name_of_country    AUSTRIA
year                  1677
Name: 5, dtype: object

---
## 3.3 - Filtering in pandas

### Pandas filtering, a look under the hood
In this section you will practice filtering data in Pandas. Filtering in Pandas may look a bit daunting, but it's actually quite easy. Filtering is always done by following the same pattern and to understand how Pandas filtering works under the hood, we will first investigate the result of a filter/expression. After that you'll practice by applying these filters on the sales and observations data.

Filtering is done by writing expressions that evaluate to `True` or `False`. There may be more than one expression, we can connect multiple expression by constructions such as AND and OR, you may have seen this before in mathematics or a course on logic. These expressions are often captured in a *truth table*. In pandas AND is indicated by `&` and or by `|`. 

The pattern to follow is:<br>
`dataframe[dataframe['ColumnName'] == 'Value']`

For multiple statements, we must put each expression between `(` and `)`.<br>
`dataframe[(dataframe['ColumnName'] == 'Value') & (dataframe['SomeOtherColumn'] == 'SomeOtherValue')]`

#### Question:
- Write the expression `expression = sales['name_of_country'] == 'NETHERLANDS'`
- Print out the expression, what do you see?

In [12]:
expression = sales['name_of_country'] == 'NETHERLANDS'
expression

# This results in either True or False for each for, indicating wether the condition is true or not.

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
Name: name_of_country, dtype: bool

### Bringing it together
So instead of selecting the rows by their index, we determine `True` or `False` for each row based on this expression. With this knowledge, try answer the questions below.

**Questions:**
- Find all rows in the observations dataframe where the value of 'pop' is greater than 80.
- Find all rows in the sales dataframe concerning the Netherlands.
- Now from those rows, select the bikes and year columns.
- Add an extra filter: Find the row about the Netherlands in 1675.
- Find all rows in the sales data frame where the country is Germany or France and the number of bikes are at least 49. In addition if the year is 1680, we also want to see that one.

In [13]:
# Filter pop > 80
observations[observations['pop'] > 80]

countryname  year  pop
0       Austria  1670   85
1       Austria  1671   83
2       Austria  1672   86
3       Austria  1673   81
5       Austria  1675   82
8       Austria  1678   81
14       France  1677   85
28  Netherlands  1673   90
29  Netherlands  1674   82
33  Netherlands  1678   85
34  Netherlands  1679   87
35  Switzerland  1671   87
36  Switzerland  1672   98
37  Switzerland  1673   96
38  Switzerland  1674   94
39  Switzerland  1675   99
40  Switzerland  1676  104
41  Switzerland  1677   99
42  Switzerland  1678  101
43  Switzerland  1679   93
44  Switzerland  1680   98

In [14]:
# Filter 'NETHERLANDS'
sales[sales['name_of_country'] == 'NETHERLANDS']

name_of_country  year  bikes  Unnamed: 3  Unnamed: 4 name_of_country.1  \
25     NETHERLANDS  1671     54         NaN         NaN       NETHERLANDS   
26     NETHERLANDS  1672     54         NaN         NaN       NETHERLANDS   
27     NETHERLANDS  1673     62         NaN         NaN       NETHERLANDS   
28     NETHERLANDS  1674     57         NaN         NaN       NETHERLANDS   
29     NETHERLANDS  1675     54         NaN         NaN       NETHERLANDS   
30     NETHERLANDS  1676     54         NaN         NaN       NETHERLANDS   
31     NETHERLANDS  1677     52         NaN         NaN       NETHERLANDS   
32     NETHERLANDS  1678     59         NaN         NaN       NETHERLANDS   
33     NETHERLANDS  1679     60         NaN         NaN       NETHERLANDS   

    year.1  total_turnover  
25    1671          4676.4  
26    1672          4676.4  
27    1673          5369.2  
28    1674          4936.2  
29    1675          4676.4  
30    1676          4676.4  
31    1677          4503.2  
32    1678          5109.4  
33    1679          5196.0

In [15]:
# Select columns from subset
sales[sales['name_of_country'] == 'NETHERLANDS'][['bikes', 'year']]

bikes  year
25     54  1671
26     54  1672
27     62  1673
28     57  1674
29     54  1675
30     54  1676
31     52  1677
32     59  1678
33     60  1679

In [16]:
# Multiple criteria filter
sales[(sales['name_of_country'] == 'NETHERLANDS') & (sales['year'] == 1675)]

name_of_country  year  bikes  Unnamed: 3  Unnamed: 4 name_of_country.1  \
29     NETHERLANDS  1675     54         NaN         NaN       NETHERLANDS   

    year.1  total_turnover  
29    1675          4676.4

In [20]:
# Multiple filters with & and |
sales[((sales['name_of_country'].isin(['GERMANY', 'FRANCE'])) & (sales['bikes'].between(49, 54))) | (sales['year'] == 1680)][['name_of_country', 'bikes', 'year']]

name_of_country  bikes  year
7          AUSTRIA     57  1680
8           FRANCE     49  1673
11          FRANCE     53  1676
14          FRANCE     56  1680
15         GERMANY     49  1670
16         GERMANY     49  1671
22         GERMANY     53  1678
24         GERMANY     45  1680
42     SWITZERLAND     69  1680

---
## 3.4 - Joining data

![alt text](https://i.stack.imgur.com/iJUMl.png)

Now we know what the data looks like and what to expect from it, we can start thinking about merging the `sales` and `observations` dataframes. This will give us combined data on what happened in a country during a year. Before we can start joining, should any data transformations be performed? Remember that you can inspect the data frames with the `.head()` function. 

#### Question:
- Investigate if the columns in both data frames are ready for joining, do we need to make any Transformations?
- If your answer for the previous question is 'yes', then proceed to make adjustments so the column values are aligned.

In [21]:
# Inspection
sales.head()
observations.head()

# We can use apply on a series and reassign this value. Note that we do not include the parentheses for
# str.title, since we pass the entire function
sales['name_of_country'] = sales['name_of_country'].apply(str.title)
observations['countryname'] = observations['countryname'].apply(str.title)

Now that our country names are written in the exact same way, we can perform the join we have been speaking about. What do we join on, and why? Look up the way to join on multiple columns in the pandas documentation:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html

#### Questions:
- Think of when you would use which type of join. If you wanted to find all observations and, if possible, add the sales information to them, how would the code look?
- What happens if you join on only one column, such as the country or the year? 
- What happens if you join a dataframe to itself?
- Try them all (create a df_inner, df_outer, df_left and df_right) and inspect the results to find out the effects of various joins. The following code will show you the shape of the dataframe in the format (rows, columns): `df.shape`


In [0]:
# Think of when you would use which type of join. If you wanted to find all observations and, if possible, add the sales information to them, how would the code look?

# Left join, keep all data in the left frame, join all matches from the right and fill missing values where data is missing.
# Inner join, keep all data that is present in both data frames.
# Outer join, keep all data, fill both left and right with missing values if needed.

In [ ]:
# What happens if you join on only one column, such as the country or the year?

# Joining on only one column introduces multiple matches per record which leads to an increase in rows.

In [ ]:
# What happens if you join a dataframe to itself?

# Depending on the column you might end up with the same dataframe or a larger data frame (rows and column wise)

In [29]:
# Try them all (create a df_inner, df_outer, df_left and df_right) and inspect the results to find out the effects of various joins. 
df_inner = sales.merge(observations, how='inner', left_on=['name_of_country', 'year'], 
                       right_on=['countryname', 'year'])

df_outer = sales.merge(observations, how='outer', left_on=['name_of_country', 'year'], 
                       right_on=['countryname', 'year'])

df_left = sales.merge(observations, how='left', left_on=['name_of_country', 'year'], 
                      right_on=['countryname', 'year'])

df_right = sales.merge(observations, how='right', left_on=['name_of_country', 'year'], 
                       right_on=['countryname', 'year'])

---
## 3.5 - Missing values
We now have a dataframe with all information in it. Upon closer inspection, you will see that the dataframe from the **outer join** has some missing values. Do you understand completely why this happens? 

In this section, we will inspect the missing values and deal with them in an appropriate manner. Let's clean up the dataframe from the outer join a bit

#### Questions:
- Delete all columns containing only NaN or duplicate data, making it easier to work with.
- Find all rows that have null values.
- Can we guess from which country the observations with the missing country value are?
- If you had to fill in the missing values in the 'bikes', 'total_turnover' and 'pop' columns, how would you do this? Just think about it for now, later we will actually do it.

Remember that the `isnull()` function helps you find rows containing null values.

In [30]:
# Delete all columns containing only NaN or duplicate data, making it easier to work with.
# Use dropna with axis=1 for columns and how='all' for all records, inplace=True allows us to modify the data frame in place 
df_outer.dropna(axis=1, how='all', inplace=True)

# Select relevant columns
cols = ['countryname', 'year', 'bikes', 'total_turnover', 'pop']

df_outer = df_outer[cols]

In [31]:
# Find all rows that have null values.
# Use isnull(), then use any to select all rows that include a null value.
df_outer[df_outer.isnull().any(axis=1)]

countryname  year  bikes  total_turnover   pop
15          NaN  1670   49.0          4208.7   NaN
43      Austria  1672    NaN             NaN  86.0
44      Austria  1673    NaN             NaN  81.0
45  Switzerland  1671    NaN             NaN  87.0

In [ ]:
# Can we guess from which country the observations with the missing country value are?

In [32]:
# If you had to fill in the missing values in the 'bikes', 'total_turnover' and 'pop' columns, how would you do this?

# Solution 1, dict:
df_outer.fillna({'bikes': 0, 'total_turnover': 0, 'pop': 0})

# Solution 2, loop:
for col in ['bikes', 'total_turnover', 'pop']:
    df[col].fillna(0, inplace=True)
    

countryname  year  bikes  total_turnover    pop
0       Austria  1670   60.0          5274.0   85.0
1       Austria  1671   59.0          5186.1   83.0
2       Austria  1674   53.0          4658.7   75.0
3       Austria  1675   58.0          5098.2   82.0
4       Austria  1676   56.0          4922.4   79.0
5       Austria  1677   50.0          4395.0   70.0
6       Austria  1678   57.0          5010.3   81.0
7       Austria  1680   57.0          5010.3   80.0
8        France  1673   49.0          4321.8   70.0
9        France  1674   56.0          4939.2   79.0
10       France  1675   56.0          4939.2   80.0
11       France  1676   53.0          4674.6   75.0
12       France  1677   60.0          5292.0   85.0
13       France  1678   55.0          4851.0   78.0
14       France  1680   56.0          4939.2   80.0
15          NaN  1670   49.0          4208.7    0.0
16      Germany  1671   49.0          4184.6   70.0
17      Germany  1672   56.0          4782.4   80.0
18      Germany  1673   48.0          4099.2   69.0
19      Germany  1675   45.0          3843.0   64.0
20      Germany  1676   48.0          4099.2   68.0
21      Germany  1677   44.0          3757.6   63.0
22      Germany  1678   53.0          4526.2   75.0
23      Germany  1679   55.0          4697.0   79.0
24      Germany  1680   45.0          3843.0   64.0
25  Netherlands  1671   54.0          4676.4   79.0
26  Netherlands  1672   54.0          4676.4   79.0
27  Netherlands  1673   62.0          5369.2   90.0
28  Netherlands  1674   57.0          4936.2   82.0
29  Netherlands  1675   54.0          4676.4   79.0
30  Netherlands  1676   54.0          4676.4   79.0
31  Netherlands  1677   52.0          4503.2   76.0
32  Netherlands  1678   59.0          5109.4   85.0
33  Netherlands  1679   60.0          5196.0   87.0
34  Switzerland  1672   69.0          6030.6   98.0
35  Switzerland  1673   68.0          5943.2   96.0
36  Switzerland  1674   66.0          5768.4   94.0
37  Switzerland  1675   70.0          6118.0   99.0
38  Switzerland  1676   73.0          6380.2  104.0
39  Switzerland  1677   70.0          6118.0   99.0
40  Switzerland  1678   71.0          6205.4  101.0
41  Switzerland  1679   66.0          5768.4   93.0
42  Switzerland  1680   69.0          6030.6   98.0
43      Austria  1672    0.0             0.0   86.0
44      Austria  1673    0.0             0.0   81.0
45  Switzerland  1671    0.0             0.0   87.0

---
## 3.6 - Aggregating data
Aggregations are useful to get a quick look at derived statistics. At Datamind we often use these derived statistics to get a better picture of our data and also to fill in missing values. In this section we will get a clear picture on how to aggregate data while grouping.

**Questions**:
- Count the number of observations per country in the dataframe.
- Calculate the average turnover per year
- Create a dataframe containing the year, average turnover per year and average population per year
- Calculate the maximum population per country.
- Calculate the sum of the total turnover per year per country. Why is this not such a sensible statistic? Take note of what happens to the NaN observations.

**Bonus**:
- Calculate, for each row, the difference between the total turnover for this observation and the average turnover for that year and store this in a new dataframe containing all old columns plus the new one. For completeness, rename the new column to something appropriate.

Hint: Create a new dataframe with the averages and join the new dataframe onto the old one. Then create a new column by subtracting one value from another:



```
df['derived_column'] = df['original_column1'] * df['original_column2']
```



In [0]:
# Count the number of observations per country in the dataframe.
df_outer.groupby('countryname').count()

In [0]:
# Calculate the average turnover per year
df_outer[['year', 'total_turnover']].groupby('year').mean()

In [0]:
# Create a dataframe containing the year, average turnover per year and average population per year
df_outer[['year', 'total_turnover', 'pop']].groupby('year').mean()

In [0]:
# Calculate the maximum population per country.
df_outer.groupby(['countryname', 'year']).sum()

In [0]:
# Calculate the sum of the total turnover per year per country. Why is this not such a sensible statistic? Take note of what happens to the NaN observations.
average_per_year = df_outer[['year', 'total_turnover']].groupby('year').mean()
df_outer2 = df_outer.merge(average_per_year, on='year', how='left')
df_outer2['diff_from_avg'] = df_outer2['total_turnover_x'] - df_outer2['total_turnover_y']

Congratulations, you've made it to the end. With the techniques used in these exercises, you can do about 80% of the work with Pandas. You could further look into the Pandas `.apply()` function and plotting.

# <br><br><center> Extra exercise </center>
## Enrich our data frame using API information and store the resulting data frame using Pandas

We can enrich our dataframe further by adding data from an API. Let's see if we can add country information to the data that we currently have. Let's use another public API to add the 2-letter ISOcode, longitude coordinates and latitude coordinates of each country that we have in our data set. This exercise is meant to take some time, feel free to experiment! This is where you learn the most.

API: https://restcountries.eu/rest/v2/name

This exercise requires you to do the following:
- Collect all countries in your data set
- Call the API for each country
- Extract the information from the **JSON** request
- Create a data frame from the API results
- Join the data to your existing data frame
- Inspect the results



In [35]:
# Get data from the API

# Get all unique countries, drop the missing value since this is not a country (!)
country_list = df_outer.dropna().countryname.unique()



In [49]:
# Call the API for each country
import requests

# Form request
response = requests.get('https://restcountries.eu/rest/v2/name/Netherlands')

# Check how the response looks like
response.json()

[{'name': 'Netherlands',
  'topLevelDomain': ['.nl'],
  'alpha2Code': 'NL',
  'alpha3Code': 'NLD',
  'callingCodes': ['31'],
  'capital': 'Amsterdam',
  'altSpellings': ['NL', 'Holland', 'Nederland'],
  'region': 'Europe',
  'subregion': 'Western Europe',
  'population': 17019800,
  'latlng': [52.5, 5.75],
  'demonym': 'Dutch',
  'area': 41850.0,
  'gini': 30.9,
  'timezones': ['UTC-04:00', 'UTC+01:00'],
  'borders': ['BEL', 'DEU'],
  'nativeName': 'Nederland',
  'numericCode': '528',
  'currencies': [{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}],
  'languages': [{'iso639_1': 'nl',
    'iso639_2': 'nld',
    'name': 'Dutch',
    'nativeName': 'Nederlands'}],
  'translations': {'de': 'Niederlande',
   'es': 'Países Bajos',
   'fr': 'Pays-Bas',
   'ja': 'オランダ',
   'it': 'Paesi Bassi',
   'br': 'Holanda',
   'pt': 'Países Baixos',
   'nl': 'Nederland',
   'hr': 'Nizozemska',
   'fa': 'پادشاهی هلند'},
  'flag': 'https://restcountries.eu/data/nld.svg',
  'regionalBlocs': [{'acronym': 'EU'

In [50]:
# We'd like to take the population from each country, for this we make a loop and store the results in a list
result = []
for country in country_list:
    response = requests.get('https://restcountries.eu/rest/v2/name/' + country)
    json = response.json()[0]  # We do [0] because a list is returned in this specific case

    population = json['population']
    country_code = json['alpha2Code']

    # We store a tuple () with the information in the result list. This allows us to easily make a data frame.
    result.append((country, population, country_code))  

In [51]:
result

[('Austria', 8725931, 'AT'),
 ('France', 66710000, 'FR'),
 ('Germany', 81770900, 'DE'),
 ('Netherlands', 17019800, 'NL'),
 ('Switzerland', 8341600, 'CH')]

In [52]:
# Create data frame from results
api_dataframe = pd.DataFrame(data=result, columns=['countryname', 'population', 'countrycode'])

In [53]:
api_dataframe

countryname  population countrycode
0      Austria     8725931          AT
1       France    66710000          FR
2      Germany    81770900          DE
3  Netherlands    17019800          NL
4  Switzerland     8341600          CH

In [55]:
# Join the result to df_outer (we use left, so we keep the NA countries)
df_outer.merge(api_dataframe, on='countryname', how='left')

countryname  year  bikes  total_turnover    pop  population countrycode
0       Austria  1670   60.0          5274.0   85.0     8725931          AT
1       Austria  1671   59.0          5186.1   83.0     8725931          AT
2       Austria  1674   53.0          4658.7   75.0     8725931          AT
3       Austria  1675   58.0          5098.2   82.0     8725931          AT
4       Austria  1676   56.0          4922.4   79.0     8725931          AT
5       Austria  1677   50.0          4395.0   70.0     8725931          AT
6       Austria  1678   57.0          5010.3   81.0     8725931          AT
7       Austria  1680   57.0          5010.3   80.0     8725931          AT
8       Austria  1672    NaN             NaN   86.0     8725931          AT
9       Austria  1673    NaN             NaN   81.0     8725931          AT
10       France  1673   49.0          4321.8   70.0    66710000          FR
11       France  1674   56.0          4939.2   79.0    66710000          FR
12       France  1675   56.0          4939.2   80.0    66710000          FR
13       France  1676   53.0          4674.6   75.0    66710000          FR
14       France  1677   60.0          5292.0   85.0    66710000          FR
15       France  1678   55.0          4851.0   78.0    66710000          FR
16       France  1680   56.0          4939.2   80.0    66710000          FR
17      Germany  1671   49.0          4184.6   70.0    81770900          DE
18      Germany  1672   56.0          4782.4   80.0    81770900          DE
19      Germany  1673   48.0          4099.2   69.0    81770900          DE
20      Germany  1675   45.0          3843.0   64.0    81770900          DE
21      Germany  1676   48.0          4099.2   68.0    81770900          DE
22      Germany  1677   44.0          3757.6   63.0    81770900          DE
23      Germany  1678   53.0          4526.2   75.0    81770900          DE
24      Germany  1679   55.0          4697.0   79.0    81770900          DE
25      Germany  1680   45.0          3843.0   64.0    81770900          DE
26  Netherlands  1671   54.0          4676.4   79.0    17019800          NL
27  Netherlands  1672   54.0          4676.4   79.0    17019800          NL
28  Netherlands  1673   62.0          5369.2   90.0    17019800          NL
29  Netherlands  1674   57.0          4936.2   82.0    17019800          NL
30  Netherlands  1675   54.0          4676.4   79.0    17019800          NL
31  Netherlands  1676   54.0          4676.4   79.0    17019800          NL
32  Netherlands  1677   52.0          4503.2   76.0    17019800          NL
33  Netherlands  1678   59.0          5109.4   85.0    17019800          NL
34  Netherlands  1679   60.0          5196.0   87.0    17019800          NL
35  Switzerland  1672   69.0          6030.6   98.0     8341600          CH
36  Switzerland  1673   68.0          5943.2   96.0     8341600          CH
37  Switzerland  1674   66.0          5768.4   94.0     8341600          CH
38  Switzerland  1675   70.0          6118.0   99.0     8341600          CH
39  Switzerland  1676   73.0          6380.2  104.0     8341600          CH
40  Switzerland  1677   70.0          6118.0   99.0     8341600          CH
41  Switzerland  1678   71.0          6205.4  101.0     8341600          CH
42  Switzerland  1679   66.0          5768.4   93.0     8341600          CH
43  Switzerland  1680   69.0          6030.6   98.0     8341600          CH
44  Switzerland  1671    NaN             NaN   87.0     8341600          CH